#! /bin/bash
#PBS -l walltime=8:00:00
#PBS -l nodes=1:ppn=24
#PBS -W group_list=dragonstooth
#PBS -q normal_q
#PBS -A crawdad
#PBS -M akumar1@vt.edu
#PBS -m a
##PBS -N  

source /groups/crawdad_lab/opt/etc/crawdad_psi4vars.sh -python 3
echo "psi4 at"
which psi4
echo ""

cd $PBS_O_WORKDIR

python optrot_vg.py > Results/h2o2_aqz_optrot_mvg_zero_freq_den_40_60_80_100_120
